### PR TITLE
Add argument to bs4Accordion to turn off auto-collapsability of accordions

### PR DESCRIPTION
**Pull request by yogat3ch**
Added an argument to the bs4Accordion function to allow us to turn off the default behavior of accordions where only one accordion item can be expanded at a time. Details on how this works come from: https://stackoverflow.com/questions/22890435/how-do-you-keep-multiple-collapses-open-in-bootstrap-3

@keatonwilson copying this PR to the currently in use version of bs4Dash

### CODE REVIEW

**Comment by keatonwilson** [comment]
Ah sorry - forgot we were using the yogat3ch version of bs4Dash and not the Martin and McCoy version!

**Comment by yogat3ch** [comment]
@keatonwilson, No worries. The merges are done and I am testing for breakages now

**Comment by yogat3ch** [comment]
@keatonwilson I updated bs4Dash from RinteRface and added this PR  - it broke a test but I just fixed it and everything seems to be working fine now. 
I've updated bs4Dash on the `integrate_vulnerability_data` `dmdu` branch and tested and everything appears to be working fine. 
The bs4Dash changes will then take effect in the forthcoming PR.

**Comment by keatonwilson** [comment]
Sounds good. I'll get a PR on dmdu to incorporate the new argument in the right places soon.

**Pull request merged**
